field: 7a9a7bc1-d075-4162-a4d6-e98b490ac40c # Links
fieldLayouts:
  a7ee40f0-f025-4d1d-87d9-43284760c618:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 75e9e8b7-3d02-4fcd-bc85-dfb0ff2f5012 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cab56bf2-842e-4310-aa36-b44d15695dde
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e9f860bb-c477-48d1-abc8-d8c18db847ed # Link Style
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0aee9fca-5fda-486e-ab66-a6f1128f4a5d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 1453b9ea-d015-4bbb-86c4-42b0e3a5892e
        userCondition: null
fields:
  75e9e8b7-3d02-4fcd-bc85-dfb0ff2f5012: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: site
    type: lenz\linkfield\fields\LinkField
  e9f860bb-c477-48d1-abc8-d8c18db847ed: # Link Style
    columnSuffix: tetpagip
    contentColumnType: string
    fieldGroup: null
    handle: itemLinkStyle
    instructions: null
    name: 'Link Style'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - true
        -
          __assoc__:
            -
              - label
              - Special
            -
              - value
              - special
    translationKeyFormat: null
    translationMethod: none
    type: custommodule\fields\ButtonStyle
handle: typeLink
name: Link
sortOrder: 1
