field: 4f46c591-9460-4156-8c3d-635e0e7cb507 # Content Builder
fieldLayouts:
  9bdf35b1-388e-415e-b56d-24fd4588d0b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: de2df50a-ab50-4345-a7f9-848e3bc6bfd9 # News Overview
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e3d1411-4fae-4d26-8ed8-ecf634fbce78
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: b19bf4e9-f473-4ff3-acda-7b63e8f6efe8
        userCondition: null
fields:
  de2df50a-ab50-4345-a7f9-848e3bc6bfd9: # News Overview
    columnSuffix: rtwalunb
    contentColumnType: string(12)
    fieldGroup: null
    handle: itmeNewsOverview
    instructions: null
    name: 'News Overview'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - 'News Overview'
            -
              - value
              - newsOverview
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: typeNewsOverview
name: 'News overview'
sortOrder: 4
