field: efe60f4b-8305-42d0-8058-e9cc9d9be104 # Column
fieldLayouts:
  1ceb63dd-a725-48b4-947f-6e312a53938e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7c37a848-e829-4384-902f-23f1bd384a8c # Media
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca4a7b3f-0f20-4c53-8516-c82882a27443
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f3ad6e7-fc2e-470c-a300-37d1e058191e
        userCondition: null
fields:
  7c37a848-e829-4384-902f-23f1bd384a8c: # Media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemMedia
    instructions: null
    name: Media
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - JPG/JPEG
        - json
        - mp4
        - png
      branchLimit: null
      defaultUploadLocationSource: 'volume:8dae5110-8a0a-4593-9ddf-26d3225f6081' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:8dae5110-8a0a-4593-9ddf-26d3225f6081' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:8dae5110-8a0a-4593-9ddf-26d3225f6081' # Images
        - 'volume:b530a0c7-6ee0-4b24-81a8-7f843fd728f8' # Videos
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: typeMedia
name: Media
sortOrder: 3
