field: efe60f4b-8305-42d0-8058-e9cc9d9be104 # Column
fieldLayouts:
  5996b883-b941-45d2-9273-6ada40436a68:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3259d45c-ce84-413c-8661-0e43c313ae06 # Links
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51497b24-973b-4f63-baaf-9da18e4b5a6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d32f349-98aa-4ccb-a3f1-5e0d798283ec
        userCondition: null
fields:
  3259d45c-ce84-413c-8661-0e43c313ae06: # Links
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemLinks
    instructions: null
    name: Links
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1812588596
      columns:
        __assoc__:
          -
            - b525d7a7-e427-4bae-befa-07e3f1fa4c04 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c30ac45f-642c-425f-87a6-8a7866949f5b # Link Style
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_12_itemlinks}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: typeLinks
name: Links
sortOrder: 4
