field: 4f46c591-9460-4156-8c3d-635e0e7cb507 # Content Builder
fieldLayouts:
  2b0925b7-d075-4846-a85d-b4556a2b9213:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b56eb3ea-0b5b-43bd-aa69-3aab5598f1eb # Default Columns
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90ebc4db-0759-4889-9748-cabf83584954
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e41897e-9078-4388-b05f-a377c092fe51 # Background Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d50a418f-b9bd-4e59-bd62-ecd4ad89cfc1
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 52420d55-302c-41a0-81e1-26ae55e98638
        userCondition: null
fields:
  7e41897e-9078-4388-b05f-a377c092fe51: # Background Color
    columnSuffix: tsyyujxh
    contentColumnType: string
    fieldGroup: null
    handle: itemBgColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - bg-beige
            -
              - default
              - true
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-prim
    translationKeyFormat: null
    translationMethod: none
    type: custommodule\fields\BackgroundColor
  b56eb3ea-0b5b-43bd-aa69-3aab5598f1eb: # Default Columns
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemDefaultColumns
    instructions: null
    name: 'Default Columns'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1166816606
      columns:
        __assoc__:
          -
            - efe60f4b-8305-42d0-8058-e9cc9d9be104 # Column
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_14_itemdefaultcolumns}}'
      fieldLayout: row
      maxRows: 2
      minRows: 1
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: typeDefault
name: Default
sortOrder: 2
