field: 4f46c591-9460-4156-8c3d-635e0e7cb507 # Content Builder
fieldLayouts:
  d08279f1-b1f8-4164-bac0-010e5c4f97a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 89fc2c4d-0d0d-47ff-8c69-0d6ea0f7567b # Columns
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84ca22c8-b393-4ecb-83b9-49de54cdb3ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ddc2b656-1c7a-4188-9bfb-842744db5866 # Background Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a83788a-fdc4-404d-9aa4-93a2d9d3ea10
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 03b8a863-dc1a-432b-9f4f-bd0a5b8a1c7a
        userCondition: null
fields:
  89fc2c4d-0d0d-47ff-8c69-0d6ea0f7567b: # Columns
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemColumns
    instructions: null
    name: Columns
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1934186306
      columns:
        __assoc__:
          -
            - 4e9fd425-b957-4ff3-be4a-5938b9f22715 # Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 92a9354a-97d8-44ee-8dd2-b3c737e333c9 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7a9a7bc1-d075-4162-a4d6-e98b490ac40c # Links
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_itemcolumns}}'
      fieldLayout: row
      maxRows: 2
      minRows: 1
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  ddc2b656-1c7a-4188-9bfb-842744db5866: # Background Color
    columnSuffix: pkxaoacb
    contentColumnType: string
    fieldGroup: null
    handle: itemBgColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - bg-beige
            -
              - default
              - true
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-prim
    translationKeyFormat: null
    translationMethod: none
    type: custommodule\fields\BackgroundColor
handle: typeText
name: Text
sortOrder: 1
