field: efe60f4b-8305-42d0-8058-e9cc9d9be104 # Column
fieldLayouts:
  0f39d74e-d3b3-43b9-9963-6cfc5175a27f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d2ad8fe-d5b7-4656-86d0-9eed8bae29d3 # Small Text Container
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c5ca7b6-fe36-4770-9127-ad5575d1bb6d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5ee9f360-d849-4a80-890c-df615474d93f # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e7e1560-6e7b-499a-9c0a-b3bbbce72641
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f72168e-3c82-4bd9-8e6d-ac78b57c2444
        userCondition: null
fields:
  2d2ad8fe-d5b7-4656-86d0-9eed8bae29d3: # Small Text Container
    columnSuffix: yzkjcsxu
    contentColumnType: boolean
    fieldGroup: null
    handle: itemSmallText
    instructions: null
    name: 'Small Text Container'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  5ee9f360-d849-4a80-890c-df615474d93f: # Text
    columnSuffix: znkoawgd
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 8b8e734f-8752-481e-9aa9-fec95fe36ba6 # Default
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: true
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
      wordLimit: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\ckeditor\Field
handle: typeText
name: Text
sortOrder: 2
