field: 4f46c591-9460-4156-8c3d-635e0e7cb507 # Content Builder
fieldLayouts:
  9bdf35b1-388e-415e-b56d-24fd4588d0b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d4133031-675c-4d11-b0ef-8a138eeb9ade # Block Spacing Top
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e33c057b-122c-4c80-9f7a-3974f52905b8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e0fb1cdb-e5bc-458f-9b4e-fef47c09b77f # Block Spacing Bottom
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d795dda4-0826-4ef0-9b4a-4addea5664b2
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: b19bf4e9-f473-4ff3-acda-7b63e8f6efe8
        userCondition: null
fields:
  d4133031-675c-4d11-b0ef-8a138eeb9ade: # Block Spacing Top
    columnSuffix: bwzfsick
    contentColumnType: string
    fieldGroup: null
    handle: itemBlockSpacingTop
    instructions: null
    name: 'Block Spacing Top'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - true
        -
          __assoc__:
            -
              - label
              - 'Extra Small'
            -
              - value
              - extraSmall
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
        -
          __assoc__:
            -
              - label
              - Zero
            -
              - value
              - zero
    translationKeyFormat: null
    translationMethod: none
    type: custommodule\fields\BlockSpacing
  e0fb1cdb-e5bc-458f-9b4e-fef47c09b77f: # Block Spacing Bottom
    columnSuffix: qztmxprm
    contentColumnType: string
    fieldGroup: null
    handle: itemBlockSpacingBottom
    instructions: null
    name: 'Block Spacing Bottom'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - true
        -
          __assoc__:
            -
              - label
              - 'Extra Small'
            -
              - value
              - extraSmall
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
        -
          __assoc__:
            -
              - label
              - Zero
            -
              - value
              - zero
    translationKeyFormat: null
    translationMethod: none
    type: custommodule\fields\BlockSpacing
handle: typeNewsOverview
name: 'News overview'
sortOrder: 4
