fieldLayouts:
  e2b99324-b44f-4e72-a0a3-2f7ccff0a1b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1c2150fe-2294-48c0-b4dd-0b3e1d20f307
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 0171e195-c85c-42f0-9fa4-148a92c0ea95
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4f46c591-9460-4156-8c3d-635e0e7cb507 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e380826-2720-408e-85f7-2a2dbb02f166
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85bda095-091a-45b7-acea-b9afee8cffe4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f0be42fd-4945-4a3c-adcb-46dd667a26f4 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 254ebd9e-e7f1-4280-ad2b-acec347eebc2
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: f1cce234-ab76-4d13-aed8-62229c23a045
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 4689aaa9-5a6b-4e97-ae87-a23e939020c0 # Legal Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
