fieldLayouts:
  66b6baf7-a252-4423-ae70-ad128824498d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9d4ca9aa-1fa3-4a29-8b7d-8f45c63fd391
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d63996dc-0b3b-47b5-855a-f457d658802b # Terms and Conditions Page
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 080a8da3-9481-4abc-af1a-01dc2656c389
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: df6e1645-929f-442c-978f-cf3efbef8e8a # Privacy Policy Page
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5dc24ebc-2af5-4d6e-9cb4-d7aa669e7cab
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 02d1135a-71f5-42a3-8647-249cf5b02275
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8b8eac8c-a151-4817-ab46-27f70a4c0cff
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57199315-f5e1-4ebd-bf3e-626fdea92136
            userCondition: null
            warning: null
            width: 100
        name: Newsletter
        uid: 3685f67f-4e3a-4839-85e2-2c0940fbecc4
        userCondition: null
handle: globalGeneral
hasTitleField: false
name: General
section: bb8dbf00-82ea-486b-8682-132d200340f8 # General
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
