headingLevels:
  - 2
  - 3
  - 4
listPlugin: DocumentList
name: Default
options:
  link:
    decorators:
      openInNewTab:
        attributes:
          target: _blank
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - bulletedList
  - numberedList
  - link
  - sourceEditing
