fieldLayouts:
  f3d35611-b512-46cf-8701-2624a9948811:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d9263823-9b14-4716-a8cf-a58eac08f7a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23b0c067-0efb-4f02-80aa-b9a873382829
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
