isPublic: false
name: 'Private Schema'
scope:
  - 'sites.d8d509d1-cc9a-4a61-a77b-7769e7ae3b57:read' # $EN_SITE_NAME
  - 'sites.b6f6d186-5cd6-4c80-b9b4-79d4667ce02a:read' # $FR_SITE_NAME
  - 'sites.051521b7-5574-4a7e-99b1-152a3e47f547:read' # $DE_SITE_NAME
  - 'sites.de652190-88bf-48ed-88fd-e247f5e7ab57:read' # $NL_SITE_NAME
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.33a43470-f56d-4405-b8b8-6c964b2515d8:read' # Company Info
  - 'entrytypes.dd1a69d0-a361-489f-b127-40eea7bf5add:read' # Company Info
  - 'sections.2f55f360-211b-4361-bd20-5f6192447101:read' # Home
  - 'entrytypes.9bd85515-d13c-4f76-9def-f62d1468d9a4:read' # Home
  - 'sections.327765b0-0c02-4ab7-beea-4264af77b04b:read' # Pages
  - 'entrytypes.ad9f5000-91f6-4149-8b12-c09146c7e0ee:read' # Default
  - 'volumes.8dae5110-8a0a-4593-9ddf-26d3225f6081:read' # Images
  - 'volumes.b530a0c7-6ee0-4b24-81a8-7f843fd728f8:read' # Videos
  - 'volumes.24b73133-88ca-43fe-9e8f-35703d8ca1af:read' # Files
  - 'usergroups.everyone:read'
  - 'formieForms.all:read'
  - 'formieSubmissions.all:read'
  - 'navigationNavs.all:read'
  - 'navigationNavs.5d79bb48-078c-48b5-95e4-9f1463e41759:read' # Main Nav
  - 'seomatic.all:read'
  - 'formieSubmissions.all:edit'
  - 'formieSubmissions.all:create'
  - 'formieSubmissions.all:save'
  - 'formieSubmissions.all:delete'
