columnSuffix: null
contentColumnType: string
fieldGroup: 58803170-ce11-4a84-9471-f8c853d3d8d5 # Common
handle: fieldContentBuilder
instructions: null
name: 'Content Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_fieldcontentbuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
