columnSuffix: rxedtsbu
contentColumnType: text
fieldGroup: 35e1477e-62ea-4d49-ad49-76f17622d108 # Company Info
handle: fieldAddressLine2
instructions: null
name: 'Address Line 2'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
