columnSuffix: varyxpij
contentColumnType: text
fieldGroup: 35e1477e-62ea-4d49-ad49-76f17622d108 # Company Info
handle: fieldVAT
instructions: null
name: VAT
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
