defaultPlacement: end
enableVersioning: true
handle: faq
name: FAQ
propagationMethod: all
siteSettings:
  051521b7-5574-4a7e-99b1-152a3e47f547: # $DE_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  b6f6d186-5cd6-4c80-b9b4-79d4667ce02a: # $FR_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  d8d509d1-cc9a-4a61-a77b-7769e7ae3b57: # $EN_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  de652190-88bf-48ed-88fd-e247f5e7ab57: # $NL_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 40804fb2-9cce-4377-a4d8-feaf46cac076
type: structure
